services:
  proxy:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "${PROXY_HTTP_PORT:-80}:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mongo:7.0.12
    volumes:
      - ./runtime/db:/data/db

  api:
    build:
      context: ./apps/api
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runtime:/app/runtime
      - ./templates:/app/templates
      - ./seeds:/app/seeds
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-12h}
      SOURCE_REPO_URL: ${SOURCE_REPO_URL:-git@github.com:org/repo.git}
      BASE_ENV_PORT: ${BASE_ENV_PORT:-8001}
      ROOT_DOMAIN: ${ROOT_DOMAIN:-prmr.md}
      RUNTIME_DIR: /app/runtime/environments
      ENVIRONMENTS_FILE: /app/runtime/environments.json
      TEMPLATE_DIR: /app/templates/environment
      SEEDS_DIR: /app/seeds
      SSH_AUTH_SOCK: /ssh-agent
